/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import{ React, useRef,useEffect} from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('./Character_Idle.gltf')
  useEffect(() => {
    console.log(nodes);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/Character_Idle.gltf')
